# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapcdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='choiceable',
            field=models.BooleanField(default=True),
        ),
    ]
