# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapcdn', '0002_node_choiceable'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='provider',
            field=models.SlugField(default='minio'),
        ),
    ]
