# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
